import React,{useEffect} from 'react'
import './UniqueKey.css'

const UniqueKey = ({handleUniqueKey}) => {
  const generateUniqueKey = () => {
    const key = Math.floor(Math.random() * 1000000000000000000).toString();
    return key.replace(/(\d{6})(?=\d)/g, '$1 ');
  };

  const uniqueKey = generateUniqueKey();
  useEffect(() => {
    handleUniqueKey(uniqueKey);
  }, [])
  

  return (
    <div>
      <div className='unique-key'>
        {uniqueKey}
      </div>
      <p className='description'>(Autogenerated) Unique key is generated for the machine.</p>
    </div>
  )
}

export default UniqueKey
